config/routes.rb
MicroBlog::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy ]
  resources :micro_posts, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/home',		to: 'static_pages#home'
  match '/help',		to: 'static_pages#help'
  match '/about',		to: 'static_pages#about'
  match '/signup',		to: 'users#new'

  match '/signin',		to: 'sessions#new'
  match '/signout',		to: 'sessions#destroy', via: :delete

end

app/models/micro_post.rb
class MicroPost < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user

  default_scope order: 'micro_posts.created_at DESC'

  validates :content, presence: true, length: { maximum: 140 }	
  validates :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :micro_posts, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def feed
    MicroPost.where("user_id = ?", id)
  end

  private
  	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/micro_posts_controller.rb
class MicroPostsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user, only: :destroy	

  def index
  end

  def create
    @micro_post = current_user.micro_posts.build(params[:micro_post])
    if @micro_post.save
		flash[:success] = "MicroPost created !"
		redirect_to current_user
	else
		render 'static_pages/home'
	end
  end
  
  def destroy
	@micro_post.destroy
	redirect_back_or root_path
  end

  private 
    def correct_user
		@micro_post = current_user.micro_posts.find_by_id(params[:id])
	rescue
		redirect_to root_path
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			# sign the user in and redirect to the user show page
			sign_in user
			redirect_back_or user
		else
			# Create an error message and re-render the sign in form
			flash.now[:error] = "Invalid Email/Password combination"
			render 'new'
		end
	end

	def new
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
	@micro_post = current_user.micro_posts.build if signed_in?
	@feed_items = current_user.feed.paginate(page: params[:page]) if signed_in?
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  def new
	@user = User.new
  end

  def index
	@users = User.paginate(page: params[:page])
	#@users = User.all
  end

  def create
	@user = User.new(params[:user])
	if @user.save
		#Handle successful case here
		flash[:success] = "Welcome to the Micro Blog !"
		redirect_to @user
	else
		render 'new'
	end
  end	

  def update 
	@user = User.find(params[:id])
	if @user.update_attributes(params[:user])
      # Handle a succesful update	  
	  flash[:success] = "Profile Update"
	  sign_in @user
	  redirect_to @user
	else
		render 'edit'
	end
  end	
 
  def show
    @user = User.find(params[:id])
	@micro_posts = @user.micro_posts.paginate(page: params[:page])
  end
  
  def edit
	@user = User.find(params[:id])
  end		

  private
    def correct_user
	  @user = User.find(params[:id])
	  redirect_to(root_path) unless current_user?(@user)	
	end

	def admin_user
		@user = User.find(params[:id])
		redirect_to(root_path) unless current_user.admin?
	end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Initialize the page title
	def full_title(page_title)
		base_title = "Micro Blog";
		if page_title.empty?
			base_title;
		else
			"#{base_title} | #{page_title}"
		end
	end 
		
end

app/helpers/micro_posts_helper.rb
module MicroPostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user?(user)
		user == current_user
	end

    def signed_in_user
	  unless signed_in?
		store_location
        redirect_to signin_path, notice: "Please Sign In"
      end
    end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.fullpath
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
	# Returns the gravatar for the given user
    def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		#gravatar_url = "https://secure.gravatar.com/avatars/#{gravatar_id}.png"
		gravatar_url = "rails.png"
		image_tag(gravatar_url, atlt: user.name, class: "gravatar")
	end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorials.org"> Rails Tutorials </a>
		by Micheal Hartl
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", '#' %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>
	

app/views/layouts/_header.html.erb
	<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
			<h2><%= link_to "Micro Blog", root_path, id: "logo" %></h2>
				<nav>
					<ul id="navcontainer">
						<li><%= link_to "Home", root_path %> </li> 
						<li><%= link_to "Help", help_path %> </li> 
						<% if signed_in? %>
							<li> <%= link_to "Users", users_path %> </li>
							<li class="dropdown">
							  <a href='#' class="dropdown-toggle" data-toggle="dropdown">
							  	Account <b class="caret"></b>
							  </a>
							  <ul class="dropdown-menu">	
							  	<li> <%= link_to "Profiles", current_user %> </li>
								<li> <%= link_to "Settings", edit_user_path(current_user) %> </li>
								<li class="divider"></li>
								<li> <%= link_to "Sign Out", signout_path, method: "delete" %></li>
							  </ul>
						    </li>
						  <% else %>
							<li><%= link_to "Sign In", signin_path %> </li> 
						  <% end %>
					</ul>
				</nav>		
			</div>
		</div>
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
  	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
 	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"> <%=value %> </div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/micro_posts/_micro_post.html.erb
<li>
	<span class="content"> <%=micro_post.content %></span>
	<span class="timestamp"> Posted <%= time_ago_in_words(micro_post.created_at) %> ago</span>
	<br> </br>
	<% if current_user?(micro_post.user) %>
		<%= link_to "delete", micro_post, method: :delete, confirm: "Are you sure ?", title: micro_post.content %>
	<% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>
		

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>

	<%= will_paginate(@feed_items) %>
<% end %>

app/views/shared/_feed_item.html.erb
 <li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user"> <%= link_to feed_item.user.name, feed_item.user %> </span>
	<span class="content"> <%= feed_item.content %></span>
	<span class="timestamp"> Posted <%= time_ago_in_words(feed_item.created_at) %> ago </span>
	<br></br>
</li>
	

app/views/shared/_micro_post_form.html.erb
<%= form_for(@micro_post) do | f | %>
	<%= render 'shared/error_messages', object: f.object %>
	
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose New Post" %>
	</div>
	
	<%= f.submit "Post", class:"btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for(current_user) %>
</a>

<h1>
	<%= current_user.name %>
</h1>

<span>
	<%= link_to "view my profile", current_user %>
</span>

<span>
	<%= pluralize(current_user.micro_posts.count, "micro post") %>
</span>
<br> </br>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<% if signed_in? %>
	<div class="row">
		<aside class="span4">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/micro_post_form' %>
			</section>
		</aside>
		<div class="span8">
			<h3> MicroPost Feed </h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% else %>
	<div class="center hero-unit">
		<h1>Welcome to Demo App</h1>
	
		<h2> 
			This is the home page for Demo App
			<a href="http://www.google.com"> Google Search </a>
		</h2>

		<%= link_to "Sign up now!", signup_path , class: "btn btn-large btn-primary" %>
	</div>

	<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		<%= link_to "DELETE", method: :delete, confirm: "Are you sure?" %> </p>
	<% end %>
</li>

app/views/users/edit.html.erb
<%= provide(:title, "Edit User") %>
<h1> Update your Profile </h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>
			
			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "All Users") %>
<h1> All Users </h1>

<%= will_paginate %>
	<ul class="users">
		<%= render @users %>
	</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign Up') %>

<h1> Sign Up </h1>

<div class=row>
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>
			
			<%= f.label :password %>
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>
			
			<%= f.submit "Create My Account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div> 

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %> 
				<%= @user.name %> 
			</h1>
		</section>
	</aside>

	<div class="span8">
		<% if @user.micro_posts.any? %>
			<h3> MicroPosts (<%= @user.micro_posts.count %>) </h3>
			<ol class="microposts">
				<%= render @micro_posts %>
			</ol>
			<%= will_paginate(@micro_posts) %>
		<% end %>
	</div>
<div>